### ISSUE TITLE
Absolute paths still an issue

### ISSUE THREAD

**Issue by Cotix** [davidsblog/dweb#7]
LFI is still not fixed.

"GET a/tmp/test.txt HTTP/1.0\r\n\r\n"

Still allows me to acces files using absolute paths.

if (string_chars(args->buffer)[j] == '/' && string_chars(args->buffer)[j+1] == '/')

should probably be just 
if (string_chars(args->buffer)[j+1] == '/')

**Comment by davidsblog** [comment]
Well spotted, I will make that change now.

**Comment by davidsblog** [comment]
OK. Done.
