### ISSUE TITLE
get_header does no bound checking on input, allows for DoS

### ISSUE THREAD

**Issue by Cotix** [davidsblog/dweb#9]
get_header has this line:
`while (*ptr++!=':') ;`

If there is no : the server crashes because it keeps incrementing the pointer untill it is inaccessable, resulting in a segfault.

Requests like these result in a segfault:
`python2 -c "print 'GET / HTTP/1.0\r\nContent-Length ' + 'A'*9999 + '\r\n\r\n'" | nc localhost 8080`

**Comment by davidsblog** [comment]
Thanks.  I'll add some bounds checking in `get_header()`.

**Comment by davidsblog** [comment]
Hopefully, the bounds check fixes it.
